name: new-release

on:
  workflow_dispatch:
    inputs:
      version:
        description: New Version
        required: true
        type: string

jobs:
  tag-update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install MusicBotCI Tools
      run: |
        pip install --upgrade pip
        pip install git+https://github.com/jacob88/MusicBotCI.git@v0.0.1
    - name: Create release branch
      run: git checkout -b release/v${{ github.event.inputs.version }}
    - name: Initialize mandatory git config
      run: |
        git config user.name "GitHub Actions"
        git config user.email noreply@github.com
    - name: Update POM file for release
      run: |
        musicbotci tag-pom ${{ github.event.inputs.version }}
    - name: Commit changes
      id: make-commit
      run: |
        git add .
        git commit --message "Prepare release v${{ github.event.inputs.version }}"
        echo "::set-output name=commit::$(git rev-parse HEAD)"
    - name: Push new branch
      run: git push origin release/v${{ github.event.inputs.version }}
