name: sync-upstream

on:
  schedule:
    - cron: '30 8 1 * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          base: master
          head: master
          merge_method: merge
          pr_message: Syncing upstream master branch with jacob88 fork.
